// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudAmqp
{
    public static class GetPlugins
    {
        /// <summary>
        /// Use this data source to retrieve information about installed and available plugins for the CloudAMQP
        /// instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using CloudAmqp = Pulumi.CloudAmqp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var plugins = CloudAmqp.GetPlugins.Invoke(new()
        ///     {
        ///         InstanceId = instance.Id,
        ///         Enabled = true,
        ///         Recommended = true,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ## Dependency
        /// 
        /// This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
        /// </summary>
        public static Task<GetPluginsResult> InvokeAsync(GetPluginsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPluginsResult>("cloudamqp:index/getPlugins:getPlugins", args ?? new GetPluginsArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about installed and available plugins for the CloudAMQP
        /// instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using CloudAmqp = Pulumi.CloudAmqp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var plugins = CloudAmqp.GetPlugins.Invoke(new()
        ///     {
        ///         InstanceId = instance.Id,
        ///         Enabled = true,
        ///         Recommended = true,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ## Dependency
        /// 
        /// This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
        /// </summary>
        public static Output<GetPluginsResult> Invoke(GetPluginsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPluginsResult>("cloudamqp:index/getPlugins:getPlugins", args ?? new GetPluginsInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Use this data source to retrieve information about installed and available plugins for the CloudAMQP
        /// instance.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using CloudAmqp = Pulumi.CloudAmqp;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var plugins = CloudAmqp.GetPlugins.Invoke(new()
        ///     {
        ///         InstanceId = instance.Id,
        ///         Enabled = true,
        ///         Recommended = true,
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ## Dependency
        /// 
        /// This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
        /// </summary>
        public static Output<GetPluginsResult> Invoke(GetPluginsInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPluginsResult>("cloudamqp:index/getPlugins:getPlugins", args ?? new GetPluginsInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPluginsArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Only store enabled plugins to state.
        /// </summary>
        [Input("enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// The CloudAMQP instance identifier.
        /// </summary>
        [Input("instanceId", required: true)]
        public int InstanceId { get; set; }

        /// <summary>
        /// Only store plugins as recommended to state.
        /// </summary>
        [Input("recommended")]
        public bool? Recommended { get; set; }

        /// <summary>
        /// Only store plugins as reqired to state.
        /// </summary>
        [Input("required")]
        public bool? Required { get; set; }

        /// <summary>
        /// Configurable sleep time (seconds) for retries when requesting
        /// information about plugins. Default set to 10 seconds.
        /// </summary>
        [Input("sleep")]
        public int? Sleep { get; set; }

        /// <summary>
        /// Configurable timeout time (seconds) for retries when requesting
        /// information about plugins. Default set to 1800 seconds.
        /// </summary>
        [Input("timeout")]
        public int? Timeout { get; set; }

        public GetPluginsArgs()
        {
        }
        public static new GetPluginsArgs Empty => new GetPluginsArgs();
    }

    public sealed class GetPluginsInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// Only store enabled plugins to state.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The CloudAMQP instance identifier.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<int> InstanceId { get; set; } = null!;

        /// <summary>
        /// Only store plugins as recommended to state.
        /// </summary>
        [Input("recommended")]
        public Input<bool>? Recommended { get; set; }

        /// <summary>
        /// Only store plugins as reqired to state.
        /// </summary>
        [Input("required")]
        public Input<bool>? Required { get; set; }

        /// <summary>
        /// Configurable sleep time (seconds) for retries when requesting
        /// information about plugins. Default set to 10 seconds.
        /// </summary>
        [Input("sleep")]
        public Input<int>? Sleep { get; set; }

        /// <summary>
        /// Configurable timeout time (seconds) for retries when requesting
        /// information about plugins. Default set to 1800 seconds.
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        public GetPluginsInvokeArgs()
        {
        }
        public static new GetPluginsInvokeArgs Empty => new GetPluginsInvokeArgs();
    }


    [OutputType]
    public sealed class GetPluginsResult
    {
        /// <summary>
        /// Information if the plugin is enabled or disabled (true/false).
        /// </summary>
        public readonly bool? Enabled;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly int InstanceId;
        /// <summary>
        /// An array of plugins. Each `Plugins` block consists of the fields documented below.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetPluginsPluginResult> Plugins;
        /// <summary>
        /// Information if the plugin is recommeded (true/false).
        /// </summary>
        public readonly bool? Recommended;
        /// <summary>
        /// Information if the plugin is required (true/false).
        /// </summary>
        public readonly bool? Required;
        public readonly int? Sleep;
        public readonly int? Timeout;

        [OutputConstructor]
        private GetPluginsResult(
            bool? enabled,

            string id,

            int instanceId,

            ImmutableArray<Outputs.GetPluginsPluginResult> plugins,

            bool? recommended,

            bool? required,

            int? sleep,

            int? timeout)
        {
            Enabled = enabled;
            Id = id;
            InstanceId = instanceId;
            Plugins = plugins;
            Recommended = recommended;
            Required = required;
            Sleep = sleep;
            Timeout = timeout;
        }
    }
}
