// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.CloudAmqp
{
    /// <summary>
    /// This resource allows you to configure OAuth2 authentication for your RabbitMQ instance.
    /// 
    /// Only available for dedicated subscription plans running ***RabbitMQ***.
    /// 
    /// ## Example Usage
    /// 
    /// &lt;details&gt;
    ///   &lt;summary&gt;
    ///     &lt;b&gt;
    ///       &lt;i&gt;Basic OAuth2 configuration&lt;/i&gt;
    ///     &lt;/b&gt;
    ///   &lt;/summary&gt;
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudAmqp = Pulumi.CloudAmqp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var oauth2Config = new CloudAmqp.Oauth2Configuration("oauth2_config", new()
    ///     {
    ///         InstanceId = instance.Id,
    ///         ResourceServerId = "test-resource-server",
    ///         Issuer = "https://test-issuer.example.com",
    ///         VerifyAud = true,
    ///         OauthClientId = "test-client-id",
    ///         OauthScopes = new[]
    ///         {
    ///             "read",
    ///             "write",
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// &lt;/details&gt;
    /// 
    /// &lt;details&gt;
    ///   &lt;summary&gt;
    ///     &lt;b&gt;
    ///       &lt;i&gt;OAuth2 configuration with all optional fields&lt;/i&gt;
    ///     &lt;/b&gt;
    ///   &lt;/summary&gt;
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudAmqp = Pulumi.CloudAmqp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var oauth2Config = new CloudAmqp.Oauth2Configuration("oauth2_config", new()
    ///     {
    ///         InstanceId = instance.Id,
    ///         ResourceServerId = "test-resource-server",
    ///         Issuer = "https://test-issuer.example.com",
    ///         PreferredUsernameClaims = new[]
    ///         {
    ///             "preferred_username",
    ///             "username",
    ///         },
    ///         AdditionalScopesKeys = new[]
    ///         {
    ///             "admin",
    ///         },
    ///         ScopePrefix = "cloudamqp",
    ///         ScopeAliases = 
    ///         {
    ///             { "read", "read:all" },
    ///             { "write", "write:all" },
    ///         },
    ///         VerifyAud = true,
    ///         OauthClientId = "test-client-id",
    ///         OauthScopes = new[]
    ///         {
    ///             "read",
    ///             "write",
    ///             "admin",
    ///         },
    ///         Audience = "https://test-audience.example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// &lt;/details&gt;
    /// 
    /// &lt;details&gt;
    ///   &lt;summary&gt;
    ///     &lt;b&gt;
    ///       &lt;i&gt;Minimal OAuth2 configuration&lt;/i&gt;
    ///     &lt;/b&gt;
    ///   &lt;/summary&gt;
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using CloudAmqp = Pulumi.CloudAmqp;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var oauth2Config = new CloudAmqp.Oauth2Configuration("oauth2_config", new()
    ///     {
    ///         InstanceId = instance.Id,
    ///         ResourceServerId = "test-resource-server",
    ///         Issuer = "https://test-issuer.example.com",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// &lt;/details&gt;
    /// 
    /// ## Dependency
    /// 
    /// This resource depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
    /// 
    /// ## Notes
    /// 
    /// * Changes to `InstanceId` will force recreation of the resource.
    /// * OAuth2 configuration changes are applied asynchronously and may take some time to complete. The
    ///   resource will poll for job completion using the configured `Sleep` and `Timeout` values.
    /// * Only one OAuth2 configuration can exist per instance. Creating a new configuration will replace
    ///   any existing configuration.
    /// * After a configuration has been applied, a restart of RabbitMQ is required for the changes to take effect.
    /// </summary>
    [CloudAmqpResourceType("cloudamqp:index/oauth2Configuration:Oauth2Configuration")]
    public partial class Oauth2Configuration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of additional JWT claim keys to extract OAuth2
        /// scopes from.
        /// </summary>
        [Output("additionalScopesKeys")]
        public Output<ImmutableArray<string>> AdditionalScopesKeys { get; private set; } = null!;

        /// <summary>
        /// The audience to be passed along to the Oauth2 provider when
        /// logging in to the management interface. Must be configured for Auth0,
        /// cannot be configured for Entra ID v2.
        /// </summary>
        [Output("audience")]
        public Output<string?> Audience { get; private set; } = null!;

        /// <summary>
        /// The CloudAMQP instance ID.
        /// </summary>
        [Output("instanceId")]
        public Output<int> InstanceId { get; private set; } = null!;

        /// <summary>
        /// The issuer URL of the OAuth2 provider. This is typically
        /// the base URL of your OAuth2 provider (e.g., Auth0, Keycloak, etc.).
        /// </summary>
        [Output("issuer")]
        public Output<string> Issuer { get; private set; } = null!;

        /// <summary>
        /// OAuth2 client ID used for token validation.
        /// </summary>
        [Output("oauthClientId")]
        public Output<string?> OauthClientId { get; private set; } = null!;

        /// <summary>
        /// List of OAuth2 scopes to request. These scopes will be
        /// used when obtaining access tokens.
        /// </summary>
        [Output("oauthScopes")]
        public Output<ImmutableArray<string>> OauthScopes { get; private set; } = null!;

        /// <summary>
        /// List of JWT claims to use as the preferred username.
        /// The first claim found in the token will be used as the username.
        /// </summary>
        [Output("preferredUsernameClaims")]
        public Output<ImmutableArray<string>> PreferredUsernameClaims { get; private set; } = null!;

        /// <summary>
        /// Resource server identifier used to identify the resource
        /// server in OAuth2 tokens.
        /// </summary>
        [Output("resourceServerId")]
        public Output<string> ResourceServerId { get; private set; } = null!;

        /// <summary>
        /// Map of scope aliases to translate scope names. This allows
        /// mapping OAuth2 scopes to RabbitMQ permission tags.
        /// </summary>
        [Output("scopeAliases")]
        public Output<ImmutableDictionary<string, string>?> ScopeAliases { get; private set; } = null!;

        /// <summary>
        /// Prefix to add to scopes. This is useful when scopes in
        /// the JWT token need to be prefixed for RabbitMQ permissions.
        /// </summary>
        [Output("scopePrefix")]
        public Output<string?> ScopePrefix { get; private set; } = null!;

        /// <summary>
        /// Configurable sleep time in seconds between retries for
        /// OAuth2 configuration. Default set to 60 seconds.
        /// </summary>
        [Output("sleep")]
        public Output<int> Sleep { get; private set; } = null!;

        /// <summary>
        /// Configurable timeout time in seconds for OAuth2
        /// configuration. Default set to 3600 seconds.
        /// </summary>
        [Output("timeout")]
        public Output<int> Timeout { get; private set; } = null!;

        /// <summary>
        /// Whether to verify the audience claim in the JWT
        /// token. Defaults to true.
        /// </summary>
        [Output("verifyAud")]
        public Output<bool> VerifyAud { get; private set; } = null!;


        /// <summary>
        /// Create a Oauth2Configuration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Oauth2Configuration(string name, Oauth2ConfigurationArgs args, CustomResourceOptions? options = null)
            : base("cloudamqp:index/oauth2Configuration:Oauth2Configuration", name, args ?? new Oauth2ConfigurationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Oauth2Configuration(string name, Input<string> id, Oauth2ConfigurationState? state = null, CustomResourceOptions? options = null)
            : base("cloudamqp:index/oauth2Configuration:Oauth2Configuration", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Oauth2Configuration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Oauth2Configuration Get(string name, Input<string> id, Oauth2ConfigurationState? state = null, CustomResourceOptions? options = null)
        {
            return new Oauth2Configuration(name, id, state, options);
        }
    }

    public sealed class Oauth2ConfigurationArgs : global::Pulumi.ResourceArgs
    {
        [Input("additionalScopesKeys")]
        private InputList<string>? _additionalScopesKeys;

        /// <summary>
        /// List of additional JWT claim keys to extract OAuth2
        /// scopes from.
        /// </summary>
        public InputList<string> AdditionalScopesKeys
        {
            get => _additionalScopesKeys ?? (_additionalScopesKeys = new InputList<string>());
            set => _additionalScopesKeys = value;
        }

        /// <summary>
        /// The audience to be passed along to the Oauth2 provider when
        /// logging in to the management interface. Must be configured for Auth0,
        /// cannot be configured for Entra ID v2.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        /// <summary>
        /// The CloudAMQP instance ID.
        /// </summary>
        [Input("instanceId", required: true)]
        public Input<int> InstanceId { get; set; } = null!;

        /// <summary>
        /// The issuer URL of the OAuth2 provider. This is typically
        /// the base URL of your OAuth2 provider (e.g., Auth0, Keycloak, etc.).
        /// </summary>
        [Input("issuer", required: true)]
        public Input<string> Issuer { get; set; } = null!;

        /// <summary>
        /// OAuth2 client ID used for token validation.
        /// </summary>
        [Input("oauthClientId")]
        public Input<string>? OauthClientId { get; set; }

        [Input("oauthScopes")]
        private InputList<string>? _oauthScopes;

        /// <summary>
        /// List of OAuth2 scopes to request. These scopes will be
        /// used when obtaining access tokens.
        /// </summary>
        public InputList<string> OauthScopes
        {
            get => _oauthScopes ?? (_oauthScopes = new InputList<string>());
            set => _oauthScopes = value;
        }

        [Input("preferredUsernameClaims")]
        private InputList<string>? _preferredUsernameClaims;

        /// <summary>
        /// List of JWT claims to use as the preferred username.
        /// The first claim found in the token will be used as the username.
        /// </summary>
        public InputList<string> PreferredUsernameClaims
        {
            get => _preferredUsernameClaims ?? (_preferredUsernameClaims = new InputList<string>());
            set => _preferredUsernameClaims = value;
        }

        /// <summary>
        /// Resource server identifier used to identify the resource
        /// server in OAuth2 tokens.
        /// </summary>
        [Input("resourceServerId", required: true)]
        public Input<string> ResourceServerId { get; set; } = null!;

        [Input("scopeAliases")]
        private InputMap<string>? _scopeAliases;

        /// <summary>
        /// Map of scope aliases to translate scope names. This allows
        /// mapping OAuth2 scopes to RabbitMQ permission tags.
        /// </summary>
        public InputMap<string> ScopeAliases
        {
            get => _scopeAliases ?? (_scopeAliases = new InputMap<string>());
            set => _scopeAliases = value;
        }

        /// <summary>
        /// Prefix to add to scopes. This is useful when scopes in
        /// the JWT token need to be prefixed for RabbitMQ permissions.
        /// </summary>
        [Input("scopePrefix")]
        public Input<string>? ScopePrefix { get; set; }

        /// <summary>
        /// Configurable sleep time in seconds between retries for
        /// OAuth2 configuration. Default set to 60 seconds.
        /// </summary>
        [Input("sleep")]
        public Input<int>? Sleep { get; set; }

        /// <summary>
        /// Configurable timeout time in seconds for OAuth2
        /// configuration. Default set to 3600 seconds.
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        /// <summary>
        /// Whether to verify the audience claim in the JWT
        /// token. Defaults to true.
        /// </summary>
        [Input("verifyAud")]
        public Input<bool>? VerifyAud { get; set; }

        public Oauth2ConfigurationArgs()
        {
        }
        public static new Oauth2ConfigurationArgs Empty => new Oauth2ConfigurationArgs();
    }

    public sealed class Oauth2ConfigurationState : global::Pulumi.ResourceArgs
    {
        [Input("additionalScopesKeys")]
        private InputList<string>? _additionalScopesKeys;

        /// <summary>
        /// List of additional JWT claim keys to extract OAuth2
        /// scopes from.
        /// </summary>
        public InputList<string> AdditionalScopesKeys
        {
            get => _additionalScopesKeys ?? (_additionalScopesKeys = new InputList<string>());
            set => _additionalScopesKeys = value;
        }

        /// <summary>
        /// The audience to be passed along to the Oauth2 provider when
        /// logging in to the management interface. Must be configured for Auth0,
        /// cannot be configured for Entra ID v2.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        /// <summary>
        /// The CloudAMQP instance ID.
        /// </summary>
        [Input("instanceId")]
        public Input<int>? InstanceId { get; set; }

        /// <summary>
        /// The issuer URL of the OAuth2 provider. This is typically
        /// the base URL of your OAuth2 provider (e.g., Auth0, Keycloak, etc.).
        /// </summary>
        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        /// <summary>
        /// OAuth2 client ID used for token validation.
        /// </summary>
        [Input("oauthClientId")]
        public Input<string>? OauthClientId { get; set; }

        [Input("oauthScopes")]
        private InputList<string>? _oauthScopes;

        /// <summary>
        /// List of OAuth2 scopes to request. These scopes will be
        /// used when obtaining access tokens.
        /// </summary>
        public InputList<string> OauthScopes
        {
            get => _oauthScopes ?? (_oauthScopes = new InputList<string>());
            set => _oauthScopes = value;
        }

        [Input("preferredUsernameClaims")]
        private InputList<string>? _preferredUsernameClaims;

        /// <summary>
        /// List of JWT claims to use as the preferred username.
        /// The first claim found in the token will be used as the username.
        /// </summary>
        public InputList<string> PreferredUsernameClaims
        {
            get => _preferredUsernameClaims ?? (_preferredUsernameClaims = new InputList<string>());
            set => _preferredUsernameClaims = value;
        }

        /// <summary>
        /// Resource server identifier used to identify the resource
        /// server in OAuth2 tokens.
        /// </summary>
        [Input("resourceServerId")]
        public Input<string>? ResourceServerId { get; set; }

        [Input("scopeAliases")]
        private InputMap<string>? _scopeAliases;

        /// <summary>
        /// Map of scope aliases to translate scope names. This allows
        /// mapping OAuth2 scopes to RabbitMQ permission tags.
        /// </summary>
        public InputMap<string> ScopeAliases
        {
            get => _scopeAliases ?? (_scopeAliases = new InputMap<string>());
            set => _scopeAliases = value;
        }

        /// <summary>
        /// Prefix to add to scopes. This is useful when scopes in
        /// the JWT token need to be prefixed for RabbitMQ permissions.
        /// </summary>
        [Input("scopePrefix")]
        public Input<string>? ScopePrefix { get; set; }

        /// <summary>
        /// Configurable sleep time in seconds between retries for
        /// OAuth2 configuration. Default set to 60 seconds.
        /// </summary>
        [Input("sleep")]
        public Input<int>? Sleep { get; set; }

        /// <summary>
        /// Configurable timeout time in seconds for OAuth2
        /// configuration. Default set to 3600 seconds.
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        /// <summary>
        /// Whether to verify the audience claim in the JWT
        /// token. Defaults to true.
        /// </summary>
        [Input("verifyAud")]
        public Input<bool>? VerifyAud { get; set; }

        public Oauth2ConfigurationState()
        {
        }
        public static new Oauth2ConfigurationState Empty => new Oauth2ConfigurationState();
    }
}
