// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPluginsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPluginsPlainArgs Empty = new GetPluginsPlainArgs();

    /**
     * Only store enabled plugins to state.
     * 
     */
    @Import(name="enabled")
    private @Nullable Boolean enabled;

    /**
     * @return Only store enabled plugins to state.
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }

    /**
     * The CloudAMQP instance identifier.
     * 
     */
    @Import(name="instanceId", required=true)
    private Integer instanceId;

    /**
     * @return The CloudAMQP instance identifier.
     * 
     */
    public Integer instanceId() {
        return this.instanceId;
    }

    /**
     * Only store plugins as recommended to state.
     * 
     */
    @Import(name="recommended")
    private @Nullable Boolean recommended;

    /**
     * @return Only store plugins as recommended to state.
     * 
     */
    public Optional<Boolean> recommended() {
        return Optional.ofNullable(this.recommended);
    }

    /**
     * Only store plugins as reqired to state.
     * 
     */
    @Import(name="required")
    private @Nullable Boolean required;

    /**
     * @return Only store plugins as reqired to state.
     * 
     */
    public Optional<Boolean> required() {
        return Optional.ofNullable(this.required);
    }

    /**
     * Configurable sleep time (seconds) for retries when requesting
     * information about plugins. Default set to 10 seconds.
     * 
     */
    @Import(name="sleep")
    private @Nullable Integer sleep;

    /**
     * @return Configurable sleep time (seconds) for retries when requesting
     * information about plugins. Default set to 10 seconds.
     * 
     */
    public Optional<Integer> sleep() {
        return Optional.ofNullable(this.sleep);
    }

    /**
     * Configurable timeout time (seconds) for retries when requesting
     * information about plugins. Default set to 1800 seconds.
     * 
     */
    @Import(name="timeout")
    private @Nullable Integer timeout;

    /**
     * @return Configurable timeout time (seconds) for retries when requesting
     * information about plugins. Default set to 1800 seconds.
     * 
     */
    public Optional<Integer> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    private GetPluginsPlainArgs() {}

    private GetPluginsPlainArgs(GetPluginsPlainArgs $) {
        this.enabled = $.enabled;
        this.instanceId = $.instanceId;
        this.recommended = $.recommended;
        this.required = $.required;
        this.sleep = $.sleep;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPluginsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPluginsPlainArgs $;

        public Builder() {
            $ = new GetPluginsPlainArgs();
        }

        public Builder(GetPluginsPlainArgs defaults) {
            $ = new GetPluginsPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Only store enabled plugins to state.
         * 
         * @return builder
         * 
         */
        public Builder enabled(@Nullable Boolean enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param instanceId The CloudAMQP instance identifier.
         * 
         * @return builder
         * 
         */
        public Builder instanceId(Integer instanceId) {
            $.instanceId = instanceId;
            return this;
        }

        /**
         * @param recommended Only store plugins as recommended to state.
         * 
         * @return builder
         * 
         */
        public Builder recommended(@Nullable Boolean recommended) {
            $.recommended = recommended;
            return this;
        }

        /**
         * @param required Only store plugins as reqired to state.
         * 
         * @return builder
         * 
         */
        public Builder required(@Nullable Boolean required) {
            $.required = required;
            return this;
        }

        /**
         * @param sleep Configurable sleep time (seconds) for retries when requesting
         * information about plugins. Default set to 10 seconds.
         * 
         * @return builder
         * 
         */
        public Builder sleep(@Nullable Integer sleep) {
            $.sleep = sleep;
            return this;
        }

        /**
         * @param timeout Configurable timeout time (seconds) for retries when requesting
         * information about plugins. Default set to 1800 seconds.
         * 
         * @return builder
         * 
         */
        public Builder timeout(@Nullable Integer timeout) {
            $.timeout = timeout;
            return this;
        }

        public GetPluginsPlainArgs build() {
            if ($.instanceId == null) {
                throw new MissingRequiredPropertyException("GetPluginsPlainArgs", "instanceId");
            }
            return $;
        }
    }

}
