// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetPluginsCommunityPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetPluginsCommunityPlainArgs Empty = new GetPluginsCommunityPlainArgs();

    /**
     * The CloudAMQP instance identifier.
     * 
     */
    @Import(name="instanceId", required=true)
    private Integer instanceId;

    /**
     * @return The CloudAMQP instance identifier.
     * 
     */
    public Integer instanceId() {
        return this.instanceId;
    }

    @Import(name="sleep")
    private @Nullable Integer sleep;

    public Optional<Integer> sleep() {
        return Optional.ofNullable(this.sleep);
    }

    @Import(name="timeout")
    private @Nullable Integer timeout;

    public Optional<Integer> timeout() {
        return Optional.ofNullable(this.timeout);
    }

    private GetPluginsCommunityPlainArgs() {}

    private GetPluginsCommunityPlainArgs(GetPluginsCommunityPlainArgs $) {
        this.instanceId = $.instanceId;
        this.sleep = $.sleep;
        this.timeout = $.timeout;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetPluginsCommunityPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetPluginsCommunityPlainArgs $;

        public Builder() {
            $ = new GetPluginsCommunityPlainArgs();
        }

        public Builder(GetPluginsCommunityPlainArgs defaults) {
            $ = new GetPluginsCommunityPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param instanceId The CloudAMQP instance identifier.
         * 
         * @return builder
         * 
         */
        public Builder instanceId(Integer instanceId) {
            $.instanceId = instanceId;
            return this;
        }

        public Builder sleep(@Nullable Integer sleep) {
            $.sleep = sleep;
            return this;
        }

        public Builder timeout(@Nullable Integer timeout) {
            $.timeout = timeout;
            return this;
        }

        public GetPluginsCommunityPlainArgs build() {
            if ($.instanceId == null) {
                throw new MissingRequiredPropertyException("GetPluginsCommunityPlainArgs", "instanceId");
            }
            return $;
        }
    }

}
