// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IntegrationLogAgentCoralogixArgs extends com.pulumi.resources.ResourceArgs {

    public static final IntegrationLogAgentCoralogixArgs Empty = new IntegrationLogAgentCoralogixArgs();

    /**
     * Application name, used to group logs by environment
     * 
     */
    @Import(name="application")
    private @Nullable Output<String> application;

    /**
     * @return Application name, used to group logs by environment
     * 
     */
    public Optional<Output<String>> application() {
        return Optional.ofNullable(this.application);
    }

    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Coralogix private key (always starts with cxtp_...)
     * 
     */
    @Import(name="privateKey")
    private @Nullable Output<String> privateKey;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Coralogix private key (always starts with cxtp_...)
     * 
     */
    public Optional<Output<String>> privateKey() {
        return Optional.ofNullable(this.privateKey);
    }

    /**
     * Version of the write-only private_key. Increment to trigger an update when the key changes (default: 1).
     * 
     */
    @Import(name="privateKeyVersion")
    private @Nullable Output<Integer> privateKeyVersion;

    /**
     * @return Version of the write-only private_key. Increment to trigger an update when the key changes (default: 1).
     * 
     */
    public Optional<Output<Integer>> privateKeyVersion() {
        return Optional.ofNullable(this.privateKeyVersion);
    }

    /**
     * AWS region hosting the CloudWatch log group.
     * 
     */
    @Import(name="region")
    private @Nullable Output<String> region;

    /**
     * @return AWS region hosting the CloudWatch log group.
     * 
     */
    public Optional<Output<String>> region() {
        return Optional.ofNullable(this.region);
    }

    /**
     * Subsystem name, used to group logs by service within an application
     * 
     */
    @Import(name="subsystem")
    private @Nullable Output<String> subsystem;

    /**
     * @return Subsystem name, used to group logs by service within an application
     * 
     */
    public Optional<Output<String>> subsystem() {
        return Optional.ofNullable(this.subsystem);
    }

    private IntegrationLogAgentCoralogixArgs() {}

    private IntegrationLogAgentCoralogixArgs(IntegrationLogAgentCoralogixArgs $) {
        this.application = $.application;
        this.privateKey = $.privateKey;
        this.privateKeyVersion = $.privateKeyVersion;
        this.region = $.region;
        this.subsystem = $.subsystem;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IntegrationLogAgentCoralogixArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IntegrationLogAgentCoralogixArgs $;

        public Builder() {
            $ = new IntegrationLogAgentCoralogixArgs();
        }

        public Builder(IntegrationLogAgentCoralogixArgs defaults) {
            $ = new IntegrationLogAgentCoralogixArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param application Application name, used to group logs by environment
         * 
         * @return builder
         * 
         */
        public Builder application(@Nullable Output<String> application) {
            $.application = application;
            return this;
        }

        /**
         * @param application Application name, used to group logs by environment
         * 
         * @return builder
         * 
         */
        public Builder application(String application) {
            return application(Output.of(application));
        }

        /**
         * @param privateKey **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Coralogix private key (always starts with cxtp_...)
         * 
         * @return builder
         * 
         */
        public Builder privateKey(@Nullable Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        /**
         * @param privateKey **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
         * Coralogix private key (always starts with cxtp_...)
         * 
         * @return builder
         * 
         */
        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        /**
         * @param privateKeyVersion Version of the write-only private_key. Increment to trigger an update when the key changes (default: 1).
         * 
         * @return builder
         * 
         */
        public Builder privateKeyVersion(@Nullable Output<Integer> privateKeyVersion) {
            $.privateKeyVersion = privateKeyVersion;
            return this;
        }

        /**
         * @param privateKeyVersion Version of the write-only private_key. Increment to trigger an update when the key changes (default: 1).
         * 
         * @return builder
         * 
         */
        public Builder privateKeyVersion(Integer privateKeyVersion) {
            return privateKeyVersion(Output.of(privateKeyVersion));
        }

        /**
         * @param region AWS region hosting the CloudWatch log group.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region AWS region hosting the CloudWatch log group.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param subsystem Subsystem name, used to group logs by service within an application
         * 
         * @return builder
         * 
         */
        public Builder subsystem(@Nullable Output<String> subsystem) {
            $.subsystem = subsystem;
            return this;
        }

        /**
         * @param subsystem Subsystem name, used to group logs by service within an application
         * 
         * @return builder
         * 
         */
        public Builder subsystem(String subsystem) {
            return subsystem(Output.of(subsystem));
        }

        public IntegrationLogAgentCoralogixArgs build() {
            return $;
        }
    }

}
