# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

_SNAKE_TO_CAMEL_CASE_TABLE = {
    "instance_id": "instanceId",
    "message_type": "messageType",
    "peering_id": "peeringId",
    "queue_regex": "queueRegex",
    "rmq_version": "rmqVersion",
    "time_threshold": "timeThreshold",
    "value_threshold": "valueThreshold",
    "vhost_regex": "vhostRegex",
    "vpc_subnet": "vpcSubnet",
}

_CAMEL_TO_SNAKE_CASE_TABLE = {
    "instanceId": "instance_id",
    "messageType": "message_type",
    "peeringId": "peering_id",
    "queueRegex": "queue_regex",
    "rmqVersion": "rmq_version",
    "timeThreshold": "time_threshold",
    "valueThreshold": "value_threshold",
    "vhostRegex": "vhost_regex",
    "vpcSubnet": "vpc_subnet",
}
