// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package cloudamqp

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Use this data source to retrieve information about VPC for a CloudAMQP instance.
//
// Only available for CloudAMQP instances hosted in AWS.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-cloudamqp/sdk/v3/go/cloudamqp"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := cloudamqp.GetVpcInfo(ctx, &cloudamqp.GetVpcInfoArgs{
// 			InstanceId: cloudamqp_instance.Instance.Id,
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
// ## Argument reference
//
// * `instanceId` - (Required) The CloudAMQP instance identifier.
//
// ## Attributes reference
//
// All attributes reference are computed
//
// * `id`                  - The identifier for this resource.
// * `name`                - The name of the CloudAMQP instance.
// * `vpcSubnet`          - Dedicated VPC subnet.
// * `ownerId`            - AWS account identifier.
// * `securityGroupId`   - AWS security group identifier.
//
// ## Dependency
//
// This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
func GetVpcInfo(ctx *pulumi.Context, args *GetVpcInfoArgs, opts ...pulumi.InvokeOption) (*GetVpcInfoResult, error) {
	var rv GetVpcInfoResult
	err := ctx.Invoke("cloudamqp:index/getVpcInfo:getVpcInfo", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpcInfo.
type GetVpcInfoArgs struct {
	InstanceId int `pulumi:"instanceId"`
}

// A collection of values returned by getVpcInfo.
type GetVpcInfoResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id              string `pulumi:"id"`
	InstanceId      int    `pulumi:"instanceId"`
	Name            string `pulumi:"name"`
	OwnerId         string `pulumi:"ownerId"`
	SecurityGroupId string `pulumi:"securityGroupId"`
	VpcSubnet       string `pulumi:"vpcSubnet"`
}
