// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetNodesNode {
    /**
     * @return Additional added disk size
     * 
     */
    private Integer additionalDiskSize;
    /**
     * @return Availability zone the node is hosted in.
     * 
     */
    private String availabilityZone;
    /**
     * @return Is the node configured?
     * 
     */
    private Boolean configured;
    /**
     * @return Subscription plan disk size
     * 
     */
    private Integer diskSize;
    /**
     * @return Currently used Erlang version on the node.
     * 
     */
    private String erlangVersion;
    /**
     * @return Enable or disable High-performance Erlang.
     * 
     */
    private Boolean hipe;
    /**
     * @return External hostname assigned to the node.
     * 
     */
    private String hostname;
    /**
     * @return Internal hostname assigned to the node.
     * 
     */
    private String hostnameInternal;
    /**
     * @return Name of the node.
     * 
     */
    private String name;
    /**
     * @return Currently configured Rabbit MQ version on the node.
     * 
     */
    private String rabbitmqVersion;
    /**
     * @return Is the node running?
     * 
     */
    private Boolean running;

    private GetNodesNode() {}
    /**
     * @return Additional added disk size
     * 
     */
    public Integer additionalDiskSize() {
        return this.additionalDiskSize;
    }
    /**
     * @return Availability zone the node is hosted in.
     * 
     */
    public String availabilityZone() {
        return this.availabilityZone;
    }
    /**
     * @return Is the node configured?
     * 
     */
    public Boolean configured() {
        return this.configured;
    }
    /**
     * @return Subscription plan disk size
     * 
     */
    public Integer diskSize() {
        return this.diskSize;
    }
    /**
     * @return Currently used Erlang version on the node.
     * 
     */
    public String erlangVersion() {
        return this.erlangVersion;
    }
    /**
     * @return Enable or disable High-performance Erlang.
     * 
     */
    public Boolean hipe() {
        return this.hipe;
    }
    /**
     * @return External hostname assigned to the node.
     * 
     */
    public String hostname() {
        return this.hostname;
    }
    /**
     * @return Internal hostname assigned to the node.
     * 
     */
    public String hostnameInternal() {
        return this.hostnameInternal;
    }
    /**
     * @return Name of the node.
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Currently configured Rabbit MQ version on the node.
     * 
     */
    public String rabbitmqVersion() {
        return this.rabbitmqVersion;
    }
    /**
     * @return Is the node running?
     * 
     */
    public Boolean running() {
        return this.running;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetNodesNode defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer additionalDiskSize;
        private String availabilityZone;
        private Boolean configured;
        private Integer diskSize;
        private String erlangVersion;
        private Boolean hipe;
        private String hostname;
        private String hostnameInternal;
        private String name;
        private String rabbitmqVersion;
        private Boolean running;
        public Builder() {}
        public Builder(GetNodesNode defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.additionalDiskSize = defaults.additionalDiskSize;
    	      this.availabilityZone = defaults.availabilityZone;
    	      this.configured = defaults.configured;
    	      this.diskSize = defaults.diskSize;
    	      this.erlangVersion = defaults.erlangVersion;
    	      this.hipe = defaults.hipe;
    	      this.hostname = defaults.hostname;
    	      this.hostnameInternal = defaults.hostnameInternal;
    	      this.name = defaults.name;
    	      this.rabbitmqVersion = defaults.rabbitmqVersion;
    	      this.running = defaults.running;
        }

        @CustomType.Setter
        public Builder additionalDiskSize(Integer additionalDiskSize) {
            if (additionalDiskSize == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "additionalDiskSize");
            }
            this.additionalDiskSize = additionalDiskSize;
            return this;
        }
        @CustomType.Setter
        public Builder availabilityZone(String availabilityZone) {
            if (availabilityZone == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "availabilityZone");
            }
            this.availabilityZone = availabilityZone;
            return this;
        }
        @CustomType.Setter
        public Builder configured(Boolean configured) {
            if (configured == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "configured");
            }
            this.configured = configured;
            return this;
        }
        @CustomType.Setter
        public Builder diskSize(Integer diskSize) {
            if (diskSize == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "diskSize");
            }
            this.diskSize = diskSize;
            return this;
        }
        @CustomType.Setter
        public Builder erlangVersion(String erlangVersion) {
            if (erlangVersion == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "erlangVersion");
            }
            this.erlangVersion = erlangVersion;
            return this;
        }
        @CustomType.Setter
        public Builder hipe(Boolean hipe) {
            if (hipe == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "hipe");
            }
            this.hipe = hipe;
            return this;
        }
        @CustomType.Setter
        public Builder hostname(String hostname) {
            if (hostname == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "hostname");
            }
            this.hostname = hostname;
            return this;
        }
        @CustomType.Setter
        public Builder hostnameInternal(String hostnameInternal) {
            if (hostnameInternal == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "hostnameInternal");
            }
            this.hostnameInternal = hostnameInternal;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder rabbitmqVersion(String rabbitmqVersion) {
            if (rabbitmqVersion == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "rabbitmqVersion");
            }
            this.rabbitmqVersion = rabbitmqVersion;
            return this;
        }
        @CustomType.Setter
        public Builder running(Boolean running) {
            if (running == null) {
              throw new MissingRequiredPropertyException("GetNodesNode", "running");
            }
            this.running = running;
            return this;
        }
        public GetNodesNode build() {
            final var _resultValue = new GetNodesNode();
            _resultValue.additionalDiskSize = additionalDiskSize;
            _resultValue.availabilityZone = availabilityZone;
            _resultValue.configured = configured;
            _resultValue.diskSize = diskSize;
            _resultValue.erlangVersion = erlangVersion;
            _resultValue.hipe = hipe;
            _resultValue.hostname = hostname;
            _resultValue.hostnameInternal = hostnameInternal;
            _resultValue.name = name;
            _resultValue.rabbitmqVersion = rabbitmqVersion;
            _resultValue.running = running;
            return _resultValue;
        }
    }
}
