// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IntegrationMetricPrometheusSplunkV2 {
    /**
     * @return Splunk HEC endpoint URL. Example: `https://your-instance-id.splunkcloud.com:8088/services/collector`.
     * 
     */
    private String endpoint;
    /**
     * @return Additional tags to attach to metrics. Format: `key=value,key2=value2`.
     * 
     */
    private @Nullable String tags;
    /**
     * @return Splunk HEC (HTTP Event Collector) token for authentication.
     * 
     */
    private String token;

    private IntegrationMetricPrometheusSplunkV2() {}
    /**
     * @return Splunk HEC endpoint URL. Example: `https://your-instance-id.splunkcloud.com:8088/services/collector`.
     * 
     */
    public String endpoint() {
        return this.endpoint;
    }
    /**
     * @return Additional tags to attach to metrics. Format: `key=value,key2=value2`.
     * 
     */
    public Optional<String> tags() {
        return Optional.ofNullable(this.tags);
    }
    /**
     * @return Splunk HEC (HTTP Event Collector) token for authentication.
     * 
     */
    public String token() {
        return this.token;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationMetricPrometheusSplunkV2 defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String endpoint;
        private @Nullable String tags;
        private String token;
        public Builder() {}
        public Builder(IntegrationMetricPrometheusSplunkV2 defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.endpoint = defaults.endpoint;
    	      this.tags = defaults.tags;
    	      this.token = defaults.token;
        }

        @CustomType.Setter
        public Builder endpoint(String endpoint) {
            if (endpoint == null) {
              throw new MissingRequiredPropertyException("IntegrationMetricPrometheusSplunkV2", "endpoint");
            }
            this.endpoint = endpoint;
            return this;
        }
        @CustomType.Setter
        public Builder tags(@Nullable String tags) {

            this.tags = tags;
            return this;
        }
        @CustomType.Setter
        public Builder token(String token) {
            if (token == null) {
              throw new MissingRequiredPropertyException("IntegrationMetricPrometheusSplunkV2", "token");
            }
            this.token = token;
            return this;
        }
        public IntegrationMetricPrometheusSplunkV2 build() {
            final var _resultValue = new IntegrationMetricPrometheusSplunkV2();
            _resultValue.endpoint = endpoint;
            _resultValue.tags = tags;
            _resultValue.token = token;
            return _resultValue;
        }
    }
}
