// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IntegrationMetricPrometheusCloudwatchV3 {
    /**
     * @return AWS IAM external ID for role assumption.
     * 
     */
    private String iamExternalId;
    /**
     * @return AWS IAM role ARN with PutMetricData permission for CloudWatch integration.
     * 
     */
    private String iamRole;
    /**
     * @return AWS region for CloudWatch metrics.
     * 
     */
    private String region;
    /**
     * @return Additional tags to attach to metrics. Format: `key=value,key2=value2`.
     * 
     */
    private @Nullable String tags;

    private IntegrationMetricPrometheusCloudwatchV3() {}
    /**
     * @return AWS IAM external ID for role assumption.
     * 
     */
    public String iamExternalId() {
        return this.iamExternalId;
    }
    /**
     * @return AWS IAM role ARN with PutMetricData permission for CloudWatch integration.
     * 
     */
    public String iamRole() {
        return this.iamRole;
    }
    /**
     * @return AWS region for CloudWatch metrics.
     * 
     */
    public String region() {
        return this.region;
    }
    /**
     * @return Additional tags to attach to metrics. Format: `key=value,key2=value2`.
     * 
     */
    public Optional<String> tags() {
        return Optional.ofNullable(this.tags);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationMetricPrometheusCloudwatchV3 defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String iamExternalId;
        private String iamRole;
        private String region;
        private @Nullable String tags;
        public Builder() {}
        public Builder(IntegrationMetricPrometheusCloudwatchV3 defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.iamExternalId = defaults.iamExternalId;
    	      this.iamRole = defaults.iamRole;
    	      this.region = defaults.region;
    	      this.tags = defaults.tags;
        }

        @CustomType.Setter
        public Builder iamExternalId(String iamExternalId) {
            if (iamExternalId == null) {
              throw new MissingRequiredPropertyException("IntegrationMetricPrometheusCloudwatchV3", "iamExternalId");
            }
            this.iamExternalId = iamExternalId;
            return this;
        }
        @CustomType.Setter
        public Builder iamRole(String iamRole) {
            if (iamRole == null) {
              throw new MissingRequiredPropertyException("IntegrationMetricPrometheusCloudwatchV3", "iamRole");
            }
            this.iamRole = iamRole;
            return this;
        }
        @CustomType.Setter
        public Builder region(String region) {
            if (region == null) {
              throw new MissingRequiredPropertyException("IntegrationMetricPrometheusCloudwatchV3", "region");
            }
            this.region = region;
            return this;
        }
        @CustomType.Setter
        public Builder tags(@Nullable String tags) {

            this.tags = tags;
            return this;
        }
        public IntegrationMetricPrometheusCloudwatchV3 build() {
            final var _resultValue = new IntegrationMetricPrometheusCloudwatchV3();
            _resultValue.iamExternalId = iamExternalId;
            _resultValue.iamRole = iamRole;
            _resultValue.region = region;
            _resultValue.tags = tags;
            return _resultValue;
        }
    }
}
