// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.cloudamqp.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class IntegrationLogAgentUptrace {
    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Uptrace DSN (Data Source Name) URL
     * 
     */
    private @Nullable String dsn;
    /**
     * @return Version of the write-only dsn. Increment to trigger an update when the DSN changes (default: 1).
     * 
     */
    private @Nullable Integer dsnVersion;

    private IntegrationLogAgentUptrace() {}
    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Uptrace DSN (Data Source Name) URL
     * 
     */
    public Optional<String> dsn() {
        return Optional.ofNullable(this.dsn);
    }
    /**
     * @return Version of the write-only dsn. Increment to trigger an update when the DSN changes (default: 1).
     * 
     */
    public Optional<Integer> dsnVersion() {
        return Optional.ofNullable(this.dsnVersion);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(IntegrationLogAgentUptrace defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String dsn;
        private @Nullable Integer dsnVersion;
        public Builder() {}
        public Builder(IntegrationLogAgentUptrace defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.dsn = defaults.dsn;
    	      this.dsnVersion = defaults.dsnVersion;
        }

        @CustomType.Setter
        public Builder dsn(@Nullable String dsn) {

            this.dsn = dsn;
            return this;
        }
        @CustomType.Setter
        public Builder dsnVersion(@Nullable Integer dsnVersion) {

            this.dsnVersion = dsnVersion;
            return this;
        }
        public IntegrationLogAgentUptrace build() {
            final var _resultValue = new IntegrationLogAgentUptrace();
            _resultValue.dsn = dsn;
            _resultValue.dsnVersion = dsnVersion;
            return _resultValue;
        }
    }
}
