// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about default or created alarms. Either use `alarmId` or `type` to retrieve the alarm.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const defaultCpuAlarm = cloudamqp.getAlarm({
 *     instanceId: cloudamqp_instance.instance.id,
 *     type: "cpu",
 * });
 * ```
 * ## Attributes reference
 *
 * All attributes reference are computed
 *
 * * `id`                  - The identifier for this resource.
 * * `enabled`             - Enable/disable status of the alarm.
 * * `valueThreshold`     - The value threshold that triggers the alarm.
 * * `reminderInterval`   - The reminder interval (in seconds) to resend the alarm if not resolved. Set to 0 for no reminders.
 * * `timeThreshold`      - The time interval (in seconds) the `valueThreshold` should be active before trigger an alarm.
 * * `queueRegex`         - Regular expression for which queue to check.
 * * `vhostRegex`         - Regular expression for which vhost to check
 * * `recipients`          - Identifier for recipient to be notified.
 * * `messageType`        - Message type `(total, unacked, ready)` used by queue alarm type.
 *
 * Specific attribute for `disk` alarm
 *
 * * `valueCalculation`   - Disk value threshold calculation, `(fixed, percentage)` of disk space remaining.
 *
 * ## Dependency
 *
 * This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
 *
 * ## Alarm types
 *
 * `cpu, memory, disk, queue, connection, flow, consumer, netsplit, server_unreachable, notice`
 */
export function getAlarm(args: GetAlarmArgs, opts?: pulumi.InvokeOptions): Promise<GetAlarmResult> {

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudamqp:index/getAlarm:getAlarm", {
        "alarmId": args.alarmId,
        "instanceId": args.instanceId,
        "type": args.type,
        "valueCalculation": args.valueCalculation,
    }, opts);
}

/**
 * A collection of arguments for invoking getAlarm.
 */
export interface GetAlarmArgs {
    /**
     * The alarm identifier. Either use this or `type` to give `cloudamqp.Alarm` necessary information to retrieve the alarm.
     */
    alarmId?: number;
    /**
     * The CloudAMQP instance identifier.
     */
    instanceId: number;
    /**
     * The alarm type. Either use this or `alarmId` to give `cloudamqp.Alarm` necessary information when retrieve the alarm. Supported alarm types
     */
    type?: string;
    valueCalculation?: string;
}

/**
 * A collection of values returned by getAlarm.
 */
export interface GetAlarmResult {
    readonly alarmId?: number;
    readonly enabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: number;
    readonly messageType: string;
    readonly queueRegex: string;
    readonly recipients: number[];
    readonly reminderInterval: number;
    readonly timeThreshold: number;
    readonly type?: string;
    readonly valueCalculation?: string;
    readonly valueThreshold: number;
    readonly vhostRegex: string;
}
/**
 * Use this data source to retrieve information about default or created alarms. Either use `alarmId` or `type` to retrieve the alarm.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const defaultCpuAlarm = cloudamqp.getAlarm({
 *     instanceId: cloudamqp_instance.instance.id,
 *     type: "cpu",
 * });
 * ```
 * ## Attributes reference
 *
 * All attributes reference are computed
 *
 * * `id`                  - The identifier for this resource.
 * * `enabled`             - Enable/disable status of the alarm.
 * * `valueThreshold`     - The value threshold that triggers the alarm.
 * * `reminderInterval`   - The reminder interval (in seconds) to resend the alarm if not resolved. Set to 0 for no reminders.
 * * `timeThreshold`      - The time interval (in seconds) the `valueThreshold` should be active before trigger an alarm.
 * * `queueRegex`         - Regular expression for which queue to check.
 * * `vhostRegex`         - Regular expression for which vhost to check
 * * `recipients`          - Identifier for recipient to be notified.
 * * `messageType`        - Message type `(total, unacked, ready)` used by queue alarm type.
 *
 * Specific attribute for `disk` alarm
 *
 * * `valueCalculation`   - Disk value threshold calculation, `(fixed, percentage)` of disk space remaining.
 *
 * ## Dependency
 *
 * This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
 *
 * ## Alarm types
 *
 * `cpu, memory, disk, queue, connection, flow, consumer, netsplit, server_unreachable, notice`
 */
export function getAlarmOutput(args: GetAlarmOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetAlarmResult> {
    return pulumi.output(args).apply((a: any) => getAlarm(a, opts))
}

/**
 * A collection of arguments for invoking getAlarm.
 */
export interface GetAlarmOutputArgs {
    /**
     * The alarm identifier. Either use this or `type` to give `cloudamqp.Alarm` necessary information to retrieve the alarm.
     */
    alarmId?: pulumi.Input<number>;
    /**
     * The CloudAMQP instance identifier.
     */
    instanceId: pulumi.Input<number>;
    /**
     * The alarm type. Either use this or `alarmId` to give `cloudamqp.Alarm` necessary information when retrieve the alarm. Supported alarm types
     */
    type?: pulumi.Input<string>;
    valueCalculation?: pulumi.Input<string>;
}
