// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * Use this data source to retrieve information about VPC for a CloudAMQP instance.
 *
 * Only available for CloudAMQP instances hosted in AWS.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const vpcInfo = cloudamqp.getVpcInfo({
 *     instanceId: cloudamqp_instance.instance.id,
 * });
 * ```
 * ## Argument reference
 *
 * * `instanceId` - (Required) The CloudAMQP instance identifier.
 *
 * ## Attribute reference
 *
 * * `name`                - (Computed) The name of the CloudAMQP instance.
 * * `vpcSubnet`          - (Computed) Dedicated VPC subnet.
 * * `ownerId`            - (Computed) AWS account identifier.
 * * `securityGroupId`   - (Computed) AWS security group identifier.
 *
 * ## Dependency
 *
 * This data source depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`.
 */
export function getVpcInfo(args: GetVpcInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcInfoResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("cloudamqp:index/getVpcInfo:getVpcInfo", {
        "instanceId": args.instanceId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcInfo.
 */
export interface GetVpcInfoArgs {
    instanceId: number;
}

/**
 * A collection of values returned by getVpcInfo.
 */
export interface GetVpcInfoResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId: number;
    readonly name: string;
    readonly ownerId: string;
    readonly securityGroupId: string;
    readonly vpcSubnet: string;
}
