// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getVpcGcpInfo(args?: GetVpcGcpInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetVpcGcpInfoResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("cloudamqp:index/getVpcGcpInfo:getVpcGcpInfo", {
        "instanceId": args.instanceId,
        "sleep": args.sleep,
        "timeout": args.timeout,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcGcpInfo.
 */
export interface GetVpcGcpInfoArgs {
    /**
     * The CloudAMQP instance identifier.
     *
     * ***Deprecated:*** from [v1.16.0], will be removed in next major version (v2.0)
     */
    instanceId?: number;
    /**
     * Configurable sleep time (seconds) between retries when reading peering.
     * Default set to 10 seconds.
     */
    sleep?: number;
    /**
     * Configurable timeout time (seconds) before retries times out. Default
     * set to 1800 seconds.
     */
    timeout?: number;
    /**
     * The managed VPC identifier.
     *
     * ***Note:*** Available from [v1.16.0], will be removed in next major version (v2.0)
     */
    vpcId?: string;
}

/**
 * A collection of values returned by getVpcGcpInfo.
 */
export interface GetVpcGcpInfoResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly instanceId?: number;
    /**
     * The name of the VPC.
     */
    readonly name: string;
    /**
     * VPC network uri.
     */
    readonly network: string;
    readonly sleep?: number;
    readonly timeout?: number;
    readonly vpcId?: string;
    /**
     * Dedicated VPC subnet.
     */
    readonly vpcSubnet: string;
}
export function getVpcGcpInfoOutput(args?: GetVpcGcpInfoOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVpcGcpInfoResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("cloudamqp:index/getVpcGcpInfo:getVpcGcpInfo", {
        "instanceId": args.instanceId,
        "sleep": args.sleep,
        "timeout": args.timeout,
        "vpcId": args.vpcId,
    }, opts);
}

/**
 * A collection of arguments for invoking getVpcGcpInfo.
 */
export interface GetVpcGcpInfoOutputArgs {
    /**
     * The CloudAMQP instance identifier.
     *
     * ***Deprecated:*** from [v1.16.0], will be removed in next major version (v2.0)
     */
    instanceId?: pulumi.Input<number>;
    /**
     * Configurable sleep time (seconds) between retries when reading peering.
     * Default set to 10 seconds.
     */
    sleep?: pulumi.Input<number>;
    /**
     * Configurable timeout time (seconds) before retries times out. Default
     * set to 1800 seconds.
     */
    timeout?: pulumi.Input<number>;
    /**
     * The managed VPC identifier.
     *
     * ***Note:*** Available from [v1.16.0], will be removed in next major version (v2.0)
     */
    vpcId?: pulumi.Input<string>;
}
