// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * This resource allows you to invoke actions on specific nodes or the entire cluster. Actions can target individual nodes, multiple nodes, or all nodes in the cluster at once.
 *
 * Only available for dedicated subscription plans.
 *
 * > **Note:** From version 1.41.0, this resource supports cluster-level actions (`cluster.start`, `cluster.stop`, `cluster.restart`) and the `nodeNames` list attribute for targeting multiple nodes. The `nodeName` attribute is deprecated in favor of `nodeNames`.
 *
 * ## Example Usage
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Cluster-wide broker restart (recommended for v1.41.0+)</i>
 *     </b>
 *   </summary>
 *
 * Restart the broker on all nodes of the cluster at once. Making sure the broker is stopped and started in correct order. This is the simplest approach for cluster-wide operations.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const clusterRestart = new cloudamqp.NodeActions("cluster_restart", {
 *     instanceId: instance.id,
 *     action: "cluster.restart",
 * });
 * ```
 *
 * </details>
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Restart broker on specific nodes using node_names</i>
 *     </b>
 *   </summary>
 *
 * Target specific nodes using the `nodeNames` list attribute.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const nodes = cloudamqp.getNodes({
 *     instanceId: instance.id,
 * });
 * const restartSubset = new cloudamqp.NodeActions("restart_subset", {
 *     instanceId: instance.id,
 *     action: "restart",
 *     nodeNames: [
 *         nodes.then(nodes => nodes.nodes?.[0]?.name),
 *         nodes.then(nodes => nodes.nodes?.[1]?.name),
 *     ],
 * });
 * ```
 *
 * </details>
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Reboot a single node</i>
 *     </b>
 *   </summary>
 *
 * Reboot the entire node (VM) rather than just the broker.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const nodes = cloudamqp.getNodes({
 *     instanceId: instance.id,
 * });
 * const rebootNode = new cloudamqp.NodeActions("reboot_node", {
 *     instanceId: instance.id,
 *     action: "reboot",
 *     nodeNames: [nodes.then(nodes => nodes.nodes?.[0]?.name)],
 * });
 * ```
 *
 * </details>
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Restart RabbitMQ management interface</i>
 *     </b>
 *   </summary>
 *
 * Only restart the management interface without affecting the broker.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const nodes = cloudamqp.getNodes({
 *     instanceId: instance.id,
 * });
 * const mgmtRestart = new cloudamqp.NodeActions("mgmt_restart", {
 *     instanceId: instance.id,
 *     action: "mgmt.restart",
 *     nodeNames: [nodes.then(nodes => nodes.nodes?.[0]?.name)],
 * });
 * ```
 *
 * </details>
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Combine with configuration changes</i>
 *     </b>
 *   </summary>
 *
 * Apply configuration changes and restart the cluster.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const rabbitmqConfig = new cloudamqp.RabbitConfiguration("rabbitmq_config", {
 *     instanceId: instance.id,
 *     logExchangeLevel: "info",
 * });
 * const clusterRestart = new cloudamqp.NodeActions("cluster_restart", {
 *     instanceId: instance.id,
 *     action: "cluster.restart",
 * }, {
 *     dependsOn: [rabbitmqConfig],
 * });
 * ```
 *
 * </details>
 *
 * <details>
 *   <summary>
 *     <b>
 *       <i>Legacy Usage (pre-1.41.0)</i>
 *     </b>
 *   </summary>
 *
 * These examples show the older approach using `nodeName` (singular) and chained restarts. While still supported, the cluster-level actions above are recommended for new configurations.
 *
 * **Single node restart:**
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const nodeAction = new cloudamqp.NodeActions("node_action", {
 *     instanceId: instance.id,
 *     nodeName: "<node name>",
 *     action: "restart",
 * });
 * ```
 *
 * **Chained multi-node restart:**
 *
 * > **Note:** This approach restarts nodes sequentially to minimize cluster disruption. Consider using `cluster.restart` for simpler configuration.
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as cloudamqp from "@pulumi/cloudamqp";
 *
 * const listNodes = cloudamqp.getNodes({
 *     instanceId: instance.id,
 * });
 * const restart01 = new cloudamqp.NodeActions("restart_01", {
 *     instanceId: instance.id,
 *     action: "restart",
 *     nodeName: listNodes.then(listNodes => listNodes.nodes?.[0]?.name),
 * });
 * const restart02 = new cloudamqp.NodeActions("restart_02", {
 *     instanceId: instance.id,
 *     action: "restart",
 *     nodeName: listNodes.then(listNodes => listNodes.nodes?.[1]?.name),
 * }, {
 *     dependsOn: [restart01],
 * });
 * const restart03 = new cloudamqp.NodeActions("restart_03", {
 *     instanceId: instance.id,
 *     action: "restart",
 *     nodeName: listNodes.then(listNodes => listNodes.nodes?.[2]?.name),
 * }, {
 *     dependsOn: [
 *         restart01,
 *         restart02,
 *     ],
 * });
 * ```
 *
 * </details>
 *
 * ## Action reference
 *
 * Actions are categorized by what they affect:
 *
 * ### Broker Actions
 *
 * These actions control the message broker software (RabbitMQ or LavinMQ) on the specified nodes.
 *
 * | Action  | Info                                      | Applies to        |
 * |---------|-------------------------------------------|-------------------|
 * | start   | Start the message broker                  | RabbitMQ, LavinMQ |
 * | stop    | Stop the message broker                   | RabbitMQ, LavinMQ |
 * | restart | Restart the message broker                | RabbitMQ, LavinMQ |
 *
 * ### Management Interface Actions
 *
 * These actions control the management interface without affecting the broker itself.
 *
 * | Action       | Info                                      | Applies to |
 * |--------------|-------------------------------------------|------------|
 * | mgmt.restart | Restart the RabbitMQ management interface | RabbitMQ   |
 *
 * ### Node Actions
 *
 * These actions affect the entire node (VM), not just the broker software.
 *
 * | Action | Info                                          | Applies to        |
 * |--------|-----------------------------------------------|-------------------|
 * | reboot | Reboot the entire node (VM)                   | RabbitMQ, LavinMQ |
 *
 * ### Cluster Actions
 *
 * > **Available from version 1.41.0**
 *
 * These actions operate on all nodes in the cluster simultaneously. The `nodeNames` attribute can be omitted for these actions.
 *
 * | Action          | Info                                            | Applies to        |
 * |-----------------|-------------------------------------------------|-------------------|
 * | cluster.start   | Start the message broker on all cluster nodes   | RabbitMQ, LavinMQ |
 * | cluster.stop    | Stop the message broker on all cluster nodes    | RabbitMQ, LavinMQ |
 * | cluster.restart | Restart the message broker on all cluster nodes | RabbitMQ, LavinMQ |
 *
 * ## Dependency
 *
 * This resource depends on CloudAMQP instance identifier, `cloudamqp_instance.instance.id`. For non-cluster actions, it also requires either `nodeName` or `nodeNames` to specify which nodes to act upon. Cluster-level actions automatically apply to all nodes in the cluster.
 *
 * ## Import
 *
 * This resource cannot be imported.
 */
export class NodeActions extends pulumi.CustomResource {
    /**
     * Get an existing NodeActions resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NodeActionsState, opts?: pulumi.CustomResourceOptions): NodeActions {
        return new NodeActions(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'cloudamqp:index/nodeActions:NodeActions';

    /**
     * Returns true if the given object is an instance of NodeActions.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NodeActions {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NodeActions.__pulumiType;
    }

    /**
     * The action to invoke. See Action reference below for valid values.
     */
    declare public readonly action: pulumi.Output<string>;
    /**
     * The CloudAMQP instance ID.
     */
    declare public readonly instanceId: pulumi.Output<number>;
    /**
     * The node name, e.g. `green-guinea-pig-01`. Use `nodeNames` instead. This attribute will be removed in a future version.
     *
     * @deprecated Use nodeNames instead. This attribute will be removed in a future version.
     */
    declare public readonly nodeName: pulumi.Output<string | undefined>;
    /**
     * List of node names to perform the action on, e.g. `["green-guinea-pig-01", "green-guinea-pig-02"]`. For cluster-level actions (`cluster.start`, `cluster.stop`, `cluster.restart`), this can be omitted and the action will automatically apply to all nodes.
     */
    declare public readonly nodeNames: pulumi.Output<string[] | undefined>;
    /**
     * Sleep interval in seconds between polling for node status. Default: `10`.
     */
    declare public readonly sleep: pulumi.Output<number>;
    /**
     * Timeout in seconds for the action to complete. Default: `1800` (30 minutes).
     *
     * > **Note:** Either `nodeName` or `nodeNames` must be specified for non-cluster actions. Cluster actions (`cluster.start`, `cluster.stop`, `cluster.restart`) can omit both and will automatically target all nodes.
     */
    declare public readonly timeout: pulumi.Output<number>;

    /**
     * Create a NodeActions resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NodeActionsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NodeActionsArgs | NodeActionsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NodeActionsState | undefined;
            resourceInputs["action"] = state?.action;
            resourceInputs["instanceId"] = state?.instanceId;
            resourceInputs["nodeName"] = state?.nodeName;
            resourceInputs["nodeNames"] = state?.nodeNames;
            resourceInputs["sleep"] = state?.sleep;
            resourceInputs["timeout"] = state?.timeout;
        } else {
            const args = argsOrState as NodeActionsArgs | undefined;
            if (args?.action === undefined && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if (args?.instanceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'instanceId'");
            }
            resourceInputs["action"] = args?.action;
            resourceInputs["instanceId"] = args?.instanceId;
            resourceInputs["nodeName"] = args?.nodeName;
            resourceInputs["nodeNames"] = args?.nodeNames;
            resourceInputs["sleep"] = args?.sleep;
            resourceInputs["timeout"] = args?.timeout;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NodeActions.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NodeActions resources.
 */
export interface NodeActionsState {
    /**
     * The action to invoke. See Action reference below for valid values.
     */
    action?: pulumi.Input<string>;
    /**
     * The CloudAMQP instance ID.
     */
    instanceId?: pulumi.Input<number>;
    /**
     * The node name, e.g. `green-guinea-pig-01`. Use `nodeNames` instead. This attribute will be removed in a future version.
     *
     * @deprecated Use nodeNames instead. This attribute will be removed in a future version.
     */
    nodeName?: pulumi.Input<string>;
    /**
     * List of node names to perform the action on, e.g. `["green-guinea-pig-01", "green-guinea-pig-02"]`. For cluster-level actions (`cluster.start`, `cluster.stop`, `cluster.restart`), this can be omitted and the action will automatically apply to all nodes.
     */
    nodeNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Sleep interval in seconds between polling for node status. Default: `10`.
     */
    sleep?: pulumi.Input<number>;
    /**
     * Timeout in seconds for the action to complete. Default: `1800` (30 minutes).
     *
     * > **Note:** Either `nodeName` or `nodeNames` must be specified for non-cluster actions. Cluster actions (`cluster.start`, `cluster.stop`, `cluster.restart`) can omit both and will automatically target all nodes.
     */
    timeout?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a NodeActions resource.
 */
export interface NodeActionsArgs {
    /**
     * The action to invoke. See Action reference below for valid values.
     */
    action: pulumi.Input<string>;
    /**
     * The CloudAMQP instance ID.
     */
    instanceId: pulumi.Input<number>;
    /**
     * The node name, e.g. `green-guinea-pig-01`. Use `nodeNames` instead. This attribute will be removed in a future version.
     *
     * @deprecated Use nodeNames instead. This attribute will be removed in a future version.
     */
    nodeName?: pulumi.Input<string>;
    /**
     * List of node names to perform the action on, e.g. `["green-guinea-pig-01", "green-guinea-pig-02"]`. For cluster-level actions (`cluster.start`, `cluster.stop`, `cluster.restart`), this can be omitted and the action will automatically apply to all nodes.
     */
    nodeNames?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Sleep interval in seconds between polling for node status. Default: `10`.
     */
    sleep?: pulumi.Input<number>;
    /**
     * Timeout in seconds for the action to complete. Default: `1800` (30 minutes).
     *
     * > **Note:** Either `nodeName` or `nodeNames` must be specified for non-cluster actions. Cluster actions (`cluster.start`, `cluster.stop`, `cluster.restart`) can omit both and will automatically target all nodes.
     */
    timeout?: pulumi.Input<number>;
}
